# my personal development overrides over the app defaults
ENV["DATABASE_USER"] = "tarsa"
ENV["SECRET_KEY_BASE"] = "9b09c31c0ba0524b33cc2102606da4ab6efacc6f1fc94398088324ec46cc6fdb9365e13c2c5318de0ce10df231a82e073d1c49b149127f91a0ec9a11d20266e2" # generated by 'rake secret'
ENV["STARTER_PASSWORD"] = "secretpw" # password for seed.rb-created users
