# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa551bd945cce1bb6ab1770e1127f9f7b1dfe3fa99a15b728ccbea04ab0f313b70bbf67c547aec2f33f1c7e9e051cc1b571a5b00ebdae53c44bd7e6fa90b3c05

test:
  secret_key_base: 90024634df27f9155fb0ad1fc265658ff666d2f74b12eb1ec4f56221f5acb3d60fb4bfada78448e77802dcd4a4557ceae59a702ba6dd12cdc90d4ce011664472

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
